export default {
    french: {
        refundPolicyTitle: "Politique de remboursement",
        refundPolicyIntro: "Dans quels cas vous pouvez être remboursé, conformément au Code de la consommation français et à la directive européenne sur les droits des consommateurs.",
        refundPolicySection1Title: "1. Votre droit légal de rétractation",
        refundPolicySection1Content: "La loi vous accorde 14 jours pour vous rétracter après la signature du contrat (article L.221-18 du Code de la consommation), sans avoir à vous justifier. Toutefois, en signant le contrat, en validant le devis ou en réglant la première mensualité ou l'acompte, vous reconnaissez expressément demander le démarrage immédiat de la prestation et acceptez les conséquences prévues par l'article L.221-28 du Code de la consommation lorsque ce texte s'applique. Cette règle concerne les prestations proposées, notamment le développement web, les abonnements de maintenance, la post-production audiovisuelle et la réparation informatique.",
        refundPolicySection2Title: "2. Remboursement pour les sites web et abonnements",
        refundPolicySection2Content: "Remboursement possible uniquement en cas de non-conformité avérée au cahier des charges validé ou de bug critique non résolu dans un délai de 30 jours après signalement écrit. Je ne rembourse pas dans les cas suivants : changement d'avis après validation des maquettes, demande de fonctionnalités non prévues initialement, ou retard imputable au Client. L'acompte initial ou la première mensualité n'est jamais remboursable après le démarrage effectif des travaux. De plus, aucun remboursement ni suspension de dette n'est accordé si les services sont coupés ou résiliés pour défaut de paiement : conformément à l'article 4 des CGV, le non-paiement d'une mensualité entraîne la déchéance du terme et l'exigibilité immédiate de l'intégralité des sommes restant dues, que le client soit professionnel ou particulier. Les frais d'hébergement ou les licences tierces engagés pour le compte du client ne sont jamais remboursables.",
        refundPolicySection3Title: "3. Remboursement pour la post-production audiovisuelle",
        refundPolicySection3Content: "Remboursement possible uniquement si le rendu final s'écarte objectivement et de façon professionnelle du brief technique écrit et validé par les deux parties avant le démarrage, et qu'aucune correction n'est techniquement réalisable. Aucun remboursement n'est dû pour des motifs subjectifs d'ordre esthétique ou créatif dès lors que le brief validé a été respecté. Le nombre de révisions incluses est précisé dans le devis ; toute demande au-delà fait l'objet d'un devis séparé. Sans retour écrit motivé dans les 7 jours calendaires suivant la livraison, la prestation est réputée acceptée et aucun remboursement ne peut être demandé. La version sans filigrane est livrée uniquement après règlement complet du solde.",
        refundPolicySection4Title: "4. Remboursement pour les réparations informatiques",
        refundPolicySection4Content: "Garantie commerciale de 90 jours sur l'intervention et les pièces installées par mes soins, limitée au périmètre technique décrit dans le rapport d'intervention. Remboursement intégral possible si le problème technique signalé initialement persiste après réparation malgré au moins une tentative de correction, et qu'il provient directement et exclusivement de mon intervention. Je ne rembourse pas les pannes survenant sur des composants distincts de ceux traités, ni les dommages liés à une mauvaise utilisation après réparation, ni les pièces apportées par le Client. Avant toute intervention, vous êtes seul responsable de la sauvegarde de vos données. Le diagnostic constitue une prestation en soi et reste dû même en cas de refus de réparation. Toute intervention sur un appareil sous garantie constructeur est effectuée à votre demande expresse, ce qui peut entraîner la perte de cette garantie.",
        refundPolicySection5Title: "5. Comment demander un remboursement ?",
        refundPolicySection5Content: "Toute demande doit m'être adressée par écrit à l'adresse {{email}} dans un délai maximum de 14 jours calendaires suivant la livraison de la prestation ou de la pièce. Vous devez impérativement préciser votre numéro de contrat ou de facture, le motif détaillé et technique de votre demande, et joindre tous les justificatifs nécessaires (captures d'écran, rapports d'erreur). Je vous réponds sous 7 jours ouvrés. Si la demande est validée, le remboursement est effectué sous 14 jours sur le moyen de paiement initial. Aucune demande ne sera étudiée si le client présente un retard de paiement sur d'autres prestations ou mensualités en cours.",
        refundPolicySection6Title: "6. Vos garanties légales",
        refundPolicySection6Content: "En plus de ma politique de remboursement, vous bénéficiez des garanties légales applicables selon la nature de la prestation ou du bien concerné, notamment la garantie légale de conformité lorsqu'elle s'applique, ainsi que la garantie des vices cachés prévue par le Code civil. Pour les réparations informatiques, la garantie légale de conformité s'applique en particulier aux pièces détachées neuves installées lorsqu'elle est juridiquement applicable. Ces garanties légales s'appliquent indépendamment de ma politique de remboursement et ne peuvent pas être exclues.",
        refundPolicySection7Title: "7. En cas de force majeure",
        refundPolicySection7Content: "Si je ne peux pas réaliser votre prestation à cause d'un événement de force majeure (catastrophe naturelle, épidémie, cyberattaque majeure, décision gouvernementale), on peut soit reporter le projet, soit je vous rembourse au prorata strict de ce qui a déjà été techniquement réalisé."
    },

    english: {
        refundPolicyTitle: "Refund Policy",
        refundPolicyIntro: "In which cases you can be refunded, in accordance with the French Consumer Code and the European directive on consumer rights.",
        refundPolicySection1Title: "1. Your legal right of withdrawal",
        refundPolicySection1Content: "The law gives you 14 days to withdraw after signing the contract (Article L.221-18 of the French Consumer Code), without having to justify your decision. However, by signing the contract, validating the quote, or paying the first installment or deposit, you expressly acknowledge that you are requesting the immediate start of the service and accept the consequences provided for by Article L.221-28 of the French Consumer Code when that text applies. This rule concerns the services offered, including web development, maintenance subscriptions, audiovisual post-production, and computer repair.",
        refundPolicySection2Title: "2. Refund for websites and subscriptions",
        refundPolicySection2Content: "Refund is possible only in the event of proven non-compliance with the validated specifications or a critical bug not resolved within 30 days after written notice. I do not issue refunds in the following cases: change of mind after approval of the mockups, request for features not included in the initial quote, or delay attributable to the Client. The initial deposit or first monthly installment is never refundable once the work has effectively started. Furthermore, no refund or debt suspension is granted if services are suspended or terminated due to non-payment: in accordance with Article 4 of the Terms and Conditions, failure to pay a monthly installment triggers the acceleration clause, making the full remaining balance immediately due, whether the client is a business or an individual. Hosting fees or third-party licenses incurred on behalf of the client are never refundable.",
        refundPolicySection3Title: "3. Refund for audiovisual post-production",
        refundPolicySection3Content: "Refund is possible only if the final result objectively and professionally departs from the written technical brief validated by both parties before work began, and no correction is technically feasible. No refund is due for subjective aesthetic or creative reasons as long as the validated brief has been respected. The number of included revision rounds is specified in the quote; any request beyond that is subject to a separate quote. Without written and reasoned feedback within 7 calendar days following delivery, the service is deemed accepted and no refund may be requested. The version without watermark is delivered only after full payment of the balance.",
        refundPolicySection4Title: "4. Refund for computer repairs",
        refundPolicySection4Content: "A 90-day commercial warranty applies to the intervention and the parts installed by me, limited to the technical scope described in the intervention report. A full refund is possible if the technical issue originally reported persists after repair despite at least one correction attempt, and if it stems directly and exclusively from my intervention. I do not refund failures affecting components other than those treated, damage caused by misuse after repair, or parts supplied by the Client. Before any intervention, you remain solely responsible for backing up your data. The diagnostic is a service in itself and remains due even if you decline the repair. Any intervention on a device still covered by the manufacturer's warranty is carried out at your express request, which may result in the loss of that warranty.",
        refundPolicySection5Title: "5. How to request a refund?",
        refundPolicySection5Content: "Any request must be sent to me in writing at {{email}} within a maximum of 14 calendar days following delivery of the service or part. You must provide your contract or invoice number, the detailed technical reason for your request, and all necessary supporting documents (screenshots, error reports). I reply within 7 business days. If the request is approved, the refund is made within 14 days to the original payment method. No request will be reviewed if the client has overdue payments on other current services or installments.",
        refundPolicySection6Title: "6. Your legal warranties",
        refundPolicySection6Content: "In addition to my refund policy, you benefit from the legal warranties that apply depending on the nature of the service or item concerned, including the legal guarantee of conformity where applicable, as well as the hidden defects warranty provided for by the French Civil Code. For computer repairs, the legal guarantee of conformity applies in particular to newly installed spare parts when it is legally applicable. These legal warranties apply independently of my refund policy and cannot be excluded.",
        refundPolicySection7Title: "7. In case of force majeure",
        refundPolicySection7Content: "If I cannot perform your service because of a force majeure event (natural disaster, epidemic, major cyberattack, government decision), we can either postpone the project, or I will refund you strictly on a pro-rata basis for what has already been technically completed."
    }
}